version: 2
updates:

# Packages
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/avatarless"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/coloring"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/corsless"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/czws"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/flyx"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/heatbadger"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/hitx"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/iconist"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/insigne"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/instafetch"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/instaphp"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/intex"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/juicy"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/macmoji"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/oggo"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/pdfx"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/qrx"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/showcase"
  schedule:
    interval: daily

# Runtimes
- package-ecosystem: npm
  directory: "/runtimes/debug"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/runtimes/md"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/runtimes/plain"
  schedule:
    interval: daily
