name: Deploy hitx

on:
  push:
    paths:
      - 'services/hitx/**'
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy hitx
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
    with:
      projectId: "QmeMQihwt14K76baePkR9qME2t2qDAFN9cYcTwrPDKgzKn"
      projectPath: "services/hitx"
