name: Deploy qrx

on:
  push:
    paths:
      - 'services/qrx/**'
    branches:
      - "master"

concurrency:
  group: qrx-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy socky
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
    with:
      projectId: "QmV2Fw8gtvE7QaqsaYNCT6pTHQsxaUtQNxth5kQqfRBaj1"
      projectPath: "services/qrx"
