name: Deploy instafetch

on:
  push:
    paths:
      - 'services/instafetch/**'
    branches:
      - "master"

concurrency:
  group: instafetch-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy instafetch
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
    with:
      projectId: "QmYNx5CwQEkKFEFShmUE63amajh22YYbcPHNyATgjboC1F"
      projectPath: "services/instafetch"
