name: Deploy avatarless

on:
  push:
    paths:
      - 'services/avatarless/**'
    branches:
      - "master"

concurrency:
  group: avatarless-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy avatarless
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
    with:
      projectId: "QmcmfQ7hEEDnxkYnMABAPKo9uo6WUmppQetXSn2jkhtpxQ"
      projectPath: "services/avatarless"
