name: Deploy flyx

on:
  push:
    paths:
      - 'services/flyx/**'
    branches:
      - "master"

concurrency:
  group: flyx-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy flyx
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
    with:
      projectId: "QmemH1FgXJy4zQ7vEtDAV5jnBbtQUb8G5AJofcBafCJ1Yb"
      projectPath: "services/flyx"
