name: Deploy socky

on:
  push:
    paths:
      - 'services/socky/**'
    branches:
      - "master"

concurrency:
  group: socky-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy socky
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
    with:
      projectId: "prj_AAqIYRPfVQYshqMIhhYxPlenSL8T"
      projectPath: "services/socky"
