name: Deploy insigne

on:
  push:
    paths:
      - 'services/insigne/**'
    branches:
      - "master"

concurrency:
  group: insigne-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy insigne
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
    with:
      projectId: "QmXwqoWbWAXiJtpjLPYoATJRmiQUde9EgfN4QiA3kPy6oZ"
      projectPath: "services/insigne"
