name: Deploy czws

on:
  push:
    paths:
      - 'services/czws/**'
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy czws
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
    with:
      projectId: "QmZyz6XqeC59zdwTYPNnXpCfpVLzbeSJqS6F4wdynskcUu"
      projectPath: "services/czws"
