name: "Compile"

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Cache Node.js
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: NPM install
        run: npm install

      - name: Lerna install
        run: npx lerna bootstrap --no-ci

      - name: Lerna compile
        run: npx lerna run compile
